FROM mcr.microsoft.com/powershell:alpine-3.17
RUN apk update && apk add --no-cache curl tar && \
    curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-26.1.4.tgz -o docker.tgz && \
    tar -xzf docker.tgz && \
    mv docker/docker /usr/local/bin/ && \
    rm -rf docker docker.tgz
WORKDIR /app
COPY update_vps.ps1 /app/update_vps.ps1
CMD ["pwsh", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", "/app/update_vps.ps1"]
