events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Docker internal DNS resolver
        resolver 127.0.0.11 valid=10s;

        # Dashboard
        location / {
            set $upstream_dashboard "http://dashboard:80";
            proxy_pass $upstream_dashboard;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # API Gateways
        location /api/auth {
            set $upstream_auth "http://auth-service:8080";
            proxy_pass $upstream_auth;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /api/orders {
            set $upstream_orders "http://order-service:8080";
            proxy_pass $upstream_orders;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
	
	location /api/transfers {
    	    set $upstream_orders "http://order-service:8080";
            proxy_pass $upstream_orders;
    	    proxy_set_header Host $host;
    	    proxy_set_header X-Forwarded-Proto https;
	}

        location /api/vehicles {
            set $upstream_vehicles "http://vehicle-service:8080";
            proxy_pass $upstream_vehicles;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /api/notifications {
            set $upstream_notifications "http://notification-service:8080";
            proxy_pass $upstream_notifications;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /api/reports {
            set $upstream_reports "http://report-service:8080";
            proxy_pass $upstream_reports;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }

        location /api/consolidation {
            set $upstream_consolidation "http://consolidation-service:8080";
            proxy_pass $upstream_consolidation;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto https;
        }
    }
}
